import io

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.models.report_schema import DossierReport


def generate_docx(report: DossierReport) -> bytes:
    """Generate a DOCX file from a DossierReport."""
    doc = Document()

    # Style defaults
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(10.5)

    # Title
    title = doc.add_heading(level=0)
    run = title.add_run("PrepLens Interview Strategy Brief")
    run.font.color.rgb = RGBColor(79, 70, 229)  # indigo
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Meta
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(
        f"{report.report_meta.company_name} — {report.report_meta.job_title}"
    ).bold = True
    meta.add_run(f"\nGenerated: {report.report_meta.generated_at[:10]}")
    doc.add_paragraph()

    # Role Summary
    _add_section_heading(doc, "Role Summary")
    doc.add_paragraph(report.role_summary)

    # Hiring Priorities
    _add_section_heading(doc, "Likely Hiring Priorities")
    for i, p in enumerate(report.hiring_priorities, 1):
        doc.add_paragraph(f"{i}. {p}")

    # Candidate Strengths
    _add_section_heading(doc, "Your Strongest Alignment")
    for s in report.candidate_strengths:
        doc.add_paragraph(s, style="List Bullet")

    # Concerns
    _add_section_heading(doc, "Likely Concerns & Gaps")
    for c in report.candidate_concerns:
        p = doc.add_paragraph()
        run = p.add_run(f"[{c.severity.upper()}] {c.concern}")
        run.bold = True
        doc.add_paragraph(f"Mitigation: {c.mitigation}")

    # Interview Questions
    _add_section_heading(doc, "Likely Interview Questions")
    for q in report.likely_interview_questions:
        p = doc.add_paragraph()
        run = p.add_run(q.question)
        run.bold = True
        doc.add_paragraph(q.why_they_might_ask)

    # Reverse Questions
    _add_section_heading(doc, "Reverse-Interview Questions")
    for q in report.reverse_interview_questions:
        p = doc.add_paragraph()
        run = p.add_run(f"[{q.audience}] {q.question}")
        run.bold = True
        doc.add_paragraph(q.why_it_matters)

    # Positioning
    _add_section_heading(doc, "Positioning Strategy")
    for s in report.positioning_strategy:
        doc.add_paragraph(s, style="List Bullet")

    # Red Flags
    _add_section_heading(doc, "Red Flags & Unknowns")
    for r in report.red_flags_or_unknowns:
        doc.add_paragraph(r, style="List Bullet")

    # Checklist
    _add_section_heading(doc, "Preparation Checklist")
    for item in report.prep_checklist:
        doc.add_paragraph(f"☐ {item}")

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph("Generated by PrepLens")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.color.rgb = RGBColor(148, 163, 184)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _add_section_heading(doc: Document, text: str):
    heading = doc.add_heading(text, level=2)
    for run in heading.runs:
        run.font.color.rgb = RGBColor(79, 70, 229)
